sudo: false
language: python
addons:
    firefox: "latest"
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.npm"
    - "$HOME/.cache/shuup/build_resources"
env:
  - TOXENV=sanity
  - TOXENV=flake8
  - TOXENV=license_headers
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django19-nomigrations-nocoverage-browser-travis-admin
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver*.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - "nvm install 7"
        - "nvm use 7"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "npm install -g selenium-standalone@6.15.1"
        - "selenium-standalone install"
        - "selenium-standalone start &"
        - "npm install -g bower"
    - python: 3.5
      env: TOXENV=py35-django19-nomigrations-nocoverage-browser-travis-front
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver*.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - "nvm install 8"
        - "nvm use 8"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "npm install -g selenium-standalone@6.15.1"
        - "selenium-standalone install"
        - "selenium-standalone start &"
        - "npm install -g bower"
    - {python: 2.7, env: TOXENV=py27-django18-nomigrations}
    - {python: 3.4, env: TOXENV=py34-django18-nomigrations}
    # - {python: 3.4, env: TOXENV=py34-django18}
    - {python: 2.7, env: TOXENV=py27-django19-nomigrations}
    - {python: 3.5, env: TOXENV=py35-django19-nomigrations}
    - {python: 3.5, env: TOXENV=py35-django19}
    - {python: 3.6, env: TOXENV=py36-django19-nomigrations}
    - {python: 2.7, env: TOXENV=py27-django111-nomigrations}
    - {python: 3.5, env: TOXENV=py35-django111-nomigrations}
    - {python: 3.5, env: TOXENV=py35-django111-nomigrations}
    - {python: 3.6, env: TOXENV=py36-django111}
    - python: 3.6
      env: TOXENV=py36-django111-nomigrations-nocoverage-browser-travis-admin
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver*.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - "nvm install 8"
        - "nvm use 8"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "npm install -g selenium-standalone@6.15.1"
        - "selenium-standalone install"
        - "selenium-standalone start &"
        - "npm install -g bower"
    - python: 3.6
      env: TOXENV=py36-django111-nomigrations-nocoverage-browser-travis-front
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver*.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - "nvm install 8"
        - "nvm use 8"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "npm install -g selenium-standalone@6.15.1"
        - "selenium-standalone install"
        - "selenium-standalone start &"
        - "npm install -g bower"
install:
  - pip install -U pip
  - pip install tox
  - pip install coveralls
  - pip install codecov
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url $TS_ORG.testspace.com
script:
  - tox
after_script:
  - if [[ "${TOXENV}" =~ ^py ]] ; then
      testspace [${TOXENV/-/\/}]testresults.xml{.} --link=coveralls;
    fi
after_success:
  - coveralls
  - codecov
notifications:
  slack:
    secure: mkYYYt9ZQc6vR1aJltnEF1DzZ5xsNmllNcdK8fCwjeK5ZOnB1atujZ08tYxx/t57gaxhMWyJHvKdD0gvyQS6R/pAO2epXY9NqOhPVDEhqtXBpd7wUcEMTQqjSy68FSTjO94O8suC18xB55Cq+KSxm8jJt6zSFsjoffhz+4QIA67rkiNPLmAw2AHYymvVaidWMDe5UUGD7qONmdFI5wx4wOE9veboWDQ49oygiq+c4NFC/d4C108jT7l9ZTko/JF7Bim3VQI0LprGuIH2tZ6TI/3LWEhQX6XXuGr6eXuTF3nQp470yRXRs50Gh+CSY++ZUgFdRfOlg0edHt9m2Lk8j2jfeLgXYWYy1QSCnJDPRzzVIkEP4xaZCcIK7pcckV0Ytn7BP3Y09MDzSvt3+0Cm7ou16shiyy5NqW5DonarN21Mlz9/auZPawsXJqYZVDIZQiM7GLJnpg9wBfgKlPxUZKwi5ttsvrS7iPNK1sSLmICFqukrQlMQnpY5h45uGXsqL7fI7z30Ftld6qIGGVFdFjh3K+4dVXV5XKHnynaR518JvugxLwrNcIWwpyB2I3Ak7AsMzd3IWnY4yrB6pSbVdG0W3zZYXR6GUsYmxICKv5pUVnRKtp2tgOKA3EwgnVjSkJahGPp5bc3xJN8mNOaR33f3kieM5jJcNteEWueX+eA=
